### ISSUE TITLE
MineOS plugin does not install

### ISSUE THREAD

**Issue by jovaniedelacruz** [freenas/iocage-ix-plugins#224]
MineOS plugin does not install correctly. I've fiddled with several combinations of flags for the SSH portion to no avail. Seems like a lot of the packages are not available. 

When I try to install it through GUI the plugin fails to install with error code:
`Error: mineOS had a failure Exception: RuntimeError Message: pkg error: - www/node8 :,www/npm-node8 :,java/openjdk8-jre :,ftp/wget :,shells/bash : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed`

When I try to install it via SSH:

`root@freenas[~]# iocage fetch --plugins dhcp=1 vnet=1 nat=1 allow_raw_sockets=1
...

Type the number of the desired plugin
Press [Enter] or type EXIT to quit: 13
Plugin: mineos
  Official Plugin: False
  Using RELEASE: 11.3-RELEASE
  Using Branch: 11.3-RELEASE
  Post-install Artifact: https://github.com/jsegaert/iocage-plugin-mineos.git
  These pkgs will be installed:

   - sysutils/rdiff-backup
     - sysutils/screen
       - net/rsync
       - devel/gmake
       - devel/git-lite
       - lang/python2
       - www/node8
       - www/npm-node8
       - java/openjdk8-jre
       - ftp/wget
       - shells/bash
         bpf should be disabled when nat is being enabled.
         Traceback (most recent call last):
         File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_create.py", line 495, in _create_jail
         value, config = iocjson.json_check_prop(key, value, config)
         File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_json.py", line 2201, in json_check_prop
         'message': f'{other_key} should be disabled '
         File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_common.py", line 103, in logit
         callback(content, exception)
         File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_common.py", line 90, in callback
         raise SystemExit(1)
         SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_plugin.py", line 296, in fetch_plugin
    jaildir, _conf, repo_dir = self.__fetch_plugin_create__(props)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_plugin.py", line 540, in __fetch_plugin_create__
    callback=self.callback
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_create.py", line 100, in create_jail
    return self._create_jail(jail_uuid, location)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_create.py", line 505, in _create_jail
    exit(1)
  File "/usr/local/lib/python3.7/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/iocage_cli/fetch.py", line 181, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/iocage.py", line 1014, in fetch
    props, accept_license=accept, official=official)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_plugin.py", line 970, in fetch_plugin_index
    self.fetch_plugin(props, 0, accept_license)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_plugin.py", line 307, in fetch_plugin
    iocage_lib.ioc_destroy.IOCDestroy().destroy_jail(location)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_destroy.py", line 272, in destroy_jail
    iocage_lib.ioc_stop.IOCStop(uuid, path, silent=True)
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_stop.py", line 62, in __init__
    raise e
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_stop.py", line 55, in __init__
    path, suppress_log=True).json_get_value('all')
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_json.py", line 1686, in json_get_value
    return self.get_full_config()
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_json.py", line 1335, in get_full_config
    conf, write = self.json_load()
  File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_json.py", line 1467, in json_load
    f'{jail_type.rstrip("s").capitalize()}:'
iocage_lib.ioc_exceptions.JailMissingConfiguration: Jail: mineos_74e5 has a missing configuration, please check that the dataset is mounted.`

**Comment by kmoore134** [comment]
Thanks! This has already been addressed by: https://github.com/freenas/iocage-ix-plugins/pull/220

We're going to be merging that in shortly for 11.3.

**Comment by jovaniedelacruz** [comment]
@kmoore134 Okay. How can I learn when it has been merged so that I can attempt to install the plugin again?

**Comment by kmoore134** [comment]
We merged it today, so in the UI if you refresh the plugins index and retry it should fetch the newest version.

**Comment by steven6282** [comment]
I see the comment on April 8th from @kmoore134 says this was merged in, but today on May 24th on the newest version of FreeNas 11.3 with a refreshed plugins index, I'm still getting this same exact error message as the original poster when trying to install the MineOS plugin.  Any updates to this problem?

**Comment by greyfade** [comment]
I'm also not seeing the fix.

I've just tried to install mineos several times today, and got a nearly identical error as above: 

>**Error:** mineos had a failure Exception: RuntimeError Message: pkg error: - sysutils/rdiff-backup :,sysutils/screen :,net/rsync :,devel/gmake :,devel/git-lite :,lang/python3 :,www/node10 :,www/npm-node10 :,java/openjdk8-jre :,ftp/wget :,shells/bash : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed

I noticed that an update version 11.3.1 was available as well, so I applied that update and tried again, and refreshed the index and tried yet again. The result is the same.

I notice also that, unlike all other plugins in the iXsystems index, MineOS does not have a "Official Plugin" badge, and the Version is listed as "N/A". I suspect this is relevant.

**Comment by Feltes** [comment]
> I notice also that, unlike all other plugins in the iXsystems index, MineOS does not have a "Official Plugin" badge, and the Version is listed as "N/A". I suspect this is relevant.

I think you're absolutely right on that. Seemed odd to me so I wasn't too surprised to see the installation fail.

**Comment by jsegaert** [comment]
This is actually another issue, but also related to a missing package because it was renamed upstream.  I submitted PR #234  to have this fixed.

**Comment by jsegaert** [comment]
For a short term workaround until this gets merged, see [this post](https://www.ixsystems.com/community/threads/mineos-unable-to-install.85048/)
